### ISSUE TITLE
SocketIO support

### ISSUE THREAD

**Issue by carmas123** [jonataslaw/get_server#31]
I'm very excited for this package, but in ma current server I use SocketIO and not simply Ws. Will we have any chance to have SocketIO support into this lib?

**Comment by Katekko** [comment]
which features do you have in socketIO that not have in get server?

**Comment by carmas123** [comment]
Nothing particular, currently I use NestJS with SocketIO and Redis support as Backend , and I was trying to understand if there were alternatives in Dart. WebSocket is not quite like SocketIO, so I was wondering if SocketIO support already existed

**Comment by Katekko** [comment]
> WebSocket is not quite like SocketIO

Right, but what is the difference between them? I'm trying to understand what you need, because you already can use socket using GetServer, and if you are using Get for flutter frontend, will be more easy connect them

**Comment by jonataslaw** [comment]
I can analyze this request for appeal, but I will state my pure opinion here.
I used socket.io for years on node.js, and 100% of my projects with socket.io had to be migrated to Uws or websockets at some point, because it has a lot of bottlenecks.
The only advantage of socket.io in my point of view, has already been overcome and has become a disadvantage, which was the possibility of working with long pooling in environments that do not support websockets. It happens that nowadays websockets have support in basically all browsers, and using Flutter (mainly using Getx that has GetConnect) you will have 100% integration, both browser, both mobile, without any effort.
So I'm going to change this discussion a little bit to:
What resource do you need in socket.io that you don't have in the websocket (and more specifically in GetSocket)?
There is already a lot of abstraction like socket.on, socket.emit, socket.join (for rooms), socket.leave (to leave rooms), and all of this with a very low cost, and low latency, which certainly surpasses much the Socket.io with node.js.

**Comment by jonataslaw** [comment]
Since this feature is not needed, I am closing this
